<?php

$params = array_merge(
        require(__DIR__ . '/../../common/config/params.php'), require(__DIR__ . '/../../common/config/params-local.php'), require(__DIR__ . '/params.php'), require(__DIR__ . '/params-local.php')
);

return [
    'id' => 'app-frontend',
    'language' => 'en', // Set the language here
    'basePath' => dirname(__DIR__),
    'bootstrap' => ['log'],
    'controllerNamespace' => 'frontend\controllers',
    'timeZone' => 'Asia/Dubai',
    'components' => [
        'authClientCollection' => [
            'class' => 'yii\authclient\Collection',
            'clients' => [
                'facebook' => [
                    'class' => 'yii\authclient\clients\Facebook',
                    'authUrl' => 'https://www.facebook.com/dialog/oauth?display=popup',
                    'clientId' => '1819694168322704',
                    'clientSecret' => '6236a14ce0f0f1158db42fe9f19d96f1',
                // 'attributeNames' => ['name', 'email', 'first_name', 'last_name'],
                ],
            ],
        ],
        'notificationManager' => [
            'class' => 'common\components\NotificationManager'
        ],
        'ApiManager' => [
            'class' => 'common\components\ApiManager'
        ],
        'DmsapiManager' => [
            'class' => 'common\components\DmsapiManager'
        ],
        'ErrorCode' => [
            'class' => 'common\components\ErrorCode'
        ],
        'CommonRequest' => [
            'class' => 'common\components\CommonRequest'
        ],
        'request' => [
            'csrfParam' => '_csrf-frontend',
            'class' => 'common\components\Request',
            'web' => '/frontend/web',
            'enableCookieValidation' => true,
            'enableCsrfValidation' => false,
        ],
        'user' => [
            'identityClass' => 'common\models\Users',
            'enableAutoLogin' => false,
            'identityCookie' => ['name' => '_identity-frontend', 'httpOnly' => true],
        ],
        'session' => [
// this is the name of the session cookie used for login on the frontend
            'name' => 'advanced-frontend',
        ],
        'log' => [
            'traceLevel' => YII_DEBUG ? 3 : 0,
            'targets' => [
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning'],
                    'categories' => ['yii\swiftmailer\Logger::add'],
                    'logFile' => '@frontend/runtime/logs/email.log',
                ],
            ],
        ],
        'errorHandler' => [
            'errorAction' => 'site/error',
        ],
        'urlManager' => [
            'enablePrettyUrl' => true,
            'showScriptName' => false,
            'rules' => [
                'get-home-contents' => 'home/get-home-contents',
                'get-tasks-contents' => 'tasks/get-tasks-contents',
                'featured-properties' => 'site/featured-properties',
                'property-details/<property:[a-zA-Z0-9_\-\.]+>' => 'site/property-details',
                'api/sample' => 'home/index',
                'login' => 'home/login',
                'register' => 'home/register',
                'api/register' => 'home/register',
                'api/login' => 'home/login',
                'api/password-reset' => 'home/request-password-reset',
                'api/set-new-password' => 'home/set-new-password',
                'api/get-profile-details' => 'user/get-profile-details',
                'api/get-settings' => 'user/get-settings',
                'api/update-profile-details' => 'user/update-profile-details',
                'api/update-settings' => 'user/update-settings',
                'api/update-password' => 'user/update-password',
                'api/localized-string' => 'home/get-mobile-string',
                'api/get-access-token' => 'home/get-access-token',
                'api/get-banner-elements' => 'home/get-banner-elements',
                'api/get-marketing-banner' => 'home/get-marketing-banner',
                'api/get-featured-banner' => 'home/get-featured-banner',
                'api/get-country-list' => 'home/get-country-list',
                'api/get-video' => 'home/get-video',
                'api/mobile-menu' => 'home/mobile-menu',
                'api/search-result' => 'home/search',
                'api/get-search-property' => 'home/get-search-property',
                'api/get-property-details' => 'home/get-property-details',
                'api/manage-favourite' => 'user/favourites',
                'api/get-favourite' => 'user/get-favourites',
                'api/get-documents' => 'user/get-documents',
                'api/get-abraj-content' => 'home/get-abraj-content',
                'api/get-contact-list' => 'user/get-contact-list',
                'api/get-booking-availability' => 'user/get-booking-availability',
                'api/get-reschedule-booking-availability' => 'user/get-reschedule-booking-availability',
                'api/booking' => 'user/booking',
                'api/get-my-requests' => 'user/get-my-requests',
                'api/reschedule' => 'user/reschedule',
                'api/cancel-booking' => 'user/cancel-booking',
                'api/get-form-elements' => 'user/get-form-elements',
                'api/post-form-data' => 'user/post-form-data',
                'api/get-notification-type' => 'user/get-notification-type',
                'api/user-notification-status' => 'user/user-notification-status',
                'api/log-out' => 'user/log-out',
                'api/contact-us' => 'home/contact-us',
                'api/get-notification' => 'user/get-notification',
                'api/read-notification' => 'user/read-notification',
                'api/add-device' => 'home/add-device',
                'api/chat' => 'user/chat',
                'api/user-property-view' => 'user/user-property-view',
                'site/activation-success' => 'site/activation-success',
                'site/activation-success' => 'site/activation-success',
                'activation' => 'home/activation',
                'documents-brouchers' => 'site/documents-brouchers',
                'email-updation' => 'user/email-updation',
                'api/get-payment-session' => 'tenant/get-payment-session',
                'api/three-d-secure' => 'tenant/three-d-secure',
                'api/transaction-pay' => 'tenant/transaction-pay',
                'api/calendar' => 'tenant/get-my-calendar',
                'api/list-calendar' => 'tenant/list-my-calendar',
                'api/incoming-leads' => 'agent/incoming-leads',
                'api/accept-booking' => 'agent/accept-booking',
                'api/agent-dashboard' => 'agent/agent-dashboard',
                'api/request-details' => 'agent/request-details',
                'api/change-booking-status' => 'agent/change-booking-status',
                'api/add-security-cheque' => 'agent/add-security-cheque',
                'api/add-twelve-cheque' => 'agent/add-twelve-cheque',
                'api/lead-summery' => 'agent/lead-summery',
                'api/upcoming-visits' => 'agent/upcoming-visits',
                'api/get-agent-profile-details' => 'agent/get-agent-profile-details',
                'api/get-corporate-discounts' => 'agent/get-corporate-discounts',
                'api/get-units' => 'agent/get-units',
                'api/cron-booking-reminder' => 'home/cron-booking-reminder',
                'api/get-maintenance-type' => 'tenant/get-maintenance-type',
                'api/maintenance' => 'tenant/maintenance',
                'api/maintenance-list' => 'tenant/maintenance-list',
                'api/cancel-maintenance' => 'tenant/cancel-maintenance',
                'api/maintenance-list' => 'tenant/maintenance-list',
                'api/maintenance-details' => 'tenant/maintenance-details',
                'api/maintenance-reschedule' => 'tenant/reschedule',
                'api/maintenance-time-availability' => 'tenant/maintenance-time-availability',
                'api/chat' => 'user/chat',
                'api/get-tenant-banner' => 'tenant/get-tenant-banner',
                'api/tenant-dashboard' => 'tenant/tenant-dashboard',
                'crm/get-units' => 'crm/get-units',
                'crm/get-agents' => 'crm/get-agents',
                'crm/post-agents' => 'crm/post-agents',
                'crm/get-token' => 'crm/get-token',
                'api/maintenance-payment' => 'tenant/maintenance-payment',
                'api/get-lease-property' => 'tenant/get-lease-property',
                'connector/property-units' => 'connector/property-units',
                'connector/agents' => 'connector/agents',
                'connector/contract-update' => 'connector/contract-update',
                'connector/server-maintenance' => 'connector/server-maintenance',
                'connector/get-access-token' => 'connector/get-access-token',
                'connector/generate-client' => 'connector/generate-client',
                'connector/maintenance-report-update' => 'connector/maintenance-report-update',
                'connector/maintenance-completion' => 'connector/maintenance-completion',
                'dms/upload-contract' => 'dms/upload-contract',
                'dms/upload-regenerate-contract' => 'dms/upload-regenerate-contract',
                'dms/upload-final-contract' => 'dms/upload-final-contract',
                'api/upload-signature' => 'user/upload-signature',
                'api/agent-contract-approval' => 'agent/agent-contract-approval',
                'api/property-booking' => 'agent/property-booking',
                'api/manual-contract-signature' => 'user/manual-contract-signature',
                'site/enquiry' => 'site/enquiry',
                'search' => 'site/search',
                'facilities-services' => 'site/facilities-services',
                'gallery' => 'site/gallery',
                'contact' => 'site/contact',
                'language/<lang:[a-zA-Z0-9_\-\.]+>' => 'site/language',
//                'api/client-booking-form/<booking_form_id:\d+>' => 'agent/client-booking-form',
                'api/client-booking-form' => 'agent/client-booking-form',
                'api/service-types' => 'tenant/service-types',
                'api/service-provider' => 'tenant/service-provider',
                'api/service-provider-products' => 'tenant/service-provider-products',
                'api/service-request' => 'tenant/service-request',
                'api/service-list' => 'tenant/service-list',
                'api/service-details' => 'tenant/service-details',
                'api/service-requests-history-list' => 'service/service-requests-history-list',
                'api/service-requests-list' => 'service/service-requests-list',
                'api/service-requests-details' => 'service/service-requests-details',
                'api/service-provider-availability' => 'service/service-provider-availability',
                'api/service-completion' => 'service/service-completion',
                'api/service-reschedule' => 'tenant/service-reschedule',
                'site/get-bedrooms' => 'site/get-bedrooms',
                'api/check-email' => 'home/check-email',
                'api/service-provider-dashboard' => 'service/service-provider-dashboard',
                'api/cancel-service' => 'tenant/cancel-service',
                'api/service-statitics' => 'service/service-statitics',
                'connector/re-generate-token' => 'connector/re-generate-token',
                'api/get-rating-questions' => 'tenant/get-rating-questions',
                'api/rating-post' => 'tenant/rating-post',
                'api/get-pending-rating-list' => 'tenant/get-pending-rating-list',
                'api/cr-user' => 'agent/cr-user',
                'api/cr-usert' => 'agent/cr-usert',
                'api/get-banks' => 'agent/get-banks',
                'api/get-dms-token' => 'site/get-dms-token',
//                'api/hosted-checkout' => 'tenant/hosted-checkout',
                'api/hosted-checkout' => 'site/hosted-checkout',
                'api/check-file' => 'dms/check-file',
                'api/download-contract' => 'site/download-contract',
                'api/update-dms-signature' => 'site/update-dms-signature',
                'api/updatetwelve' => 'site/updatetwelve',
                'api/get-document' => 'site/get-document',
                'payment-complete' => 'site/payment-complete',
                'payment-error' => 'site/payment-error',
                'payment-cancel' => 'site/payment-cancel',
                'payment-timeout' => 'site/payment-timeout',
                'sample-api' => 'site/sample-api',
                'run-cron' => 'site/run-cron',
                'api/update-dms-signature' => 'user/update-dms-signature',
                'api/update-dms-security-cheque' => 'agent/update-dms-security-cheque',
                'api/update-dms-twelve-cheque' => 'agent/update-dms-twelve-cheque',
                'api/update-dms-missing-data' => 'site/update-dms-missing-data',
                'api/how-to-use-video' => 'tenant/how-to-use-video',
                'site/check-email' => 'site/check-email',
                'daily-cron' => 'site/daily-cron',
                'api/get-exit-form-questions' => 'user/get-exit-form-questions',
                'no-preview' => 'site/no-preview',
                'api/client-creation' => 'agent/client-creation',
                'site/login' => 'site/login',
                'site/get-token' => 'site/get-token',
                'site/check-login' => 'site/check-login',
                'site/log-out' => 'site/log-out',
                'routing-management' => 'cron/routing-management',
                'get-state' => 'site/get-state',
                'get-district' => 'site/get-district',
                'site/update-property' => 'site/update-property',
                'site/create-user' => 'site/create-user',
                'clients/login' => 'clients/login',
            ]
        ],
        'mailer ' => [
            'class' => 'yii\swiftmailer\Mailer',
            'transport' => [
                'class' => 'Swift_SmtpTransport',
                'host' => 'smtp.gmail.com',
                'username' => 'support@tomsher.com',
                'password' => 'abrajbaythepearl',
                'port' => '587',
                'encryption' => 'tls',
            ],
        ],
        'formatter' => [
            'class' => 'yii\i18n\Formatter',
            'dateFormat' => 'd-M-Y',
            'datetimeFormat' => 'd-M-Y H:i:s',
            'timeFormat' => 'H:i:s',
        ]
    ],
    'params' => $params,
];
