<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Address Book' => '',
    'Adv Masters' => '',
    'Advertisement Masters' => '',
    'Advertisements' => '',
    'Are you sure you want to delete this item?' => '',
    'Auth Key' => '',
    'Banners/Advertisement' => '',
    'Category ID' => '',
    'Category Name' => '',
    'Code' => '',
    'Colors' => '',
    'Create' => '',
    'Create Advertisement Master' => '',
    'Create Advertisements' => '',
    'Create Color' => '',
    'Create Filter Group' => '',
    'Create Filters Elements' => '',
    'Create Temp Cart' => '',
    'Created At' => '',
    'Created On' => '',
    'Delete' => '',
    'Description' => '',
    'Email' => '',
    'Filter Groups' => '',
    'Filters Elements' => '',
    'First Name' => '',
    'ID' => '',
    'Language ID' => '',
    'Last Name' => '',
    'Meta Description' => '',
    'Meta Keywords' => '',
    'Meta Title' => '',
    'Metatitle' => '',
    'Name' => '',
    'Password Hash' => '',
    'Password Reset Token' => '',
    'Product ID' => '',
    'Product Name' => '',
    'Reset' => '',
    'Role' => '',
    'Save' => '',
    'Search' => '',
    'Status' => '',
    'Temp Carts' => '',
    'Update' => '',
    'Update ' => '',
    'Update {modelClass}: ' => '',
    'Updated At' => '',
    'Updated On' => '',
    'Username' => '',
];
