<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    ' You haven\'t added any addresses.' => '',
    0 => '',
    'Add New Address' => '',
    'Sell on Osole' => '',
    'Add new address' => '',
    'Address Book' => '',
    'Address Books' => '',
    'Billing Address' => '',
    'Cancel' => '',
    'Change Password' => '',
    'Checkout' => '',
    'Confirm Password' => '',
    'Country' => '',
    'Date Of Birth' => '',
    'E-mail Id' => '',
    'Edit' => '',
    'Edit Account' => '',
    'Edit Profile' => '',
    'Edit Your Personal Details' => '',
    'Il mio account' => '',
    'Login' => '',
    'Mon - Sat: 9:00AM - 18:00PM' => '',
    'My Account' => '',
    'My Dashboard' => '',
    'My Profile' => '',
    'Name' => '',
    'New Password' => '',
    'Newsletter' => '',
    'Newsletter Subscription' => '',
    'No' => '',
    'Old Password' => '',
    'Old password is incorrect' => '',
    'Order History' => '',
    'Osole : Address Book' => '',
    'Osole : Dashboard' => '',
    'Osole : Newsletter Options' => '',
    'Osole : Reset Password' => '',
    'Osole : User Profile' => '',
    'Password' => '',
    'Phone' => '',
    'Post Code' => '',
    'Register' => '',
    'Remove' => '',
    'Returns' => '',
    'Reward Points' => '',
    'Save' => '',
    'Search' => '',
    'Select date' => '',
    'Shipping Address' => '',
    'Sorry, your password cannot be rest now' => '',
    'Submit' => '',
    'Transactions' => '',
    'Wish List' => '',
    'Yes' => '',
    'Your password has reset' => '',
    'info@company.com' => '',
    'English' => '',
    'Italian' => '',
    'Language' => '',
];
